services:
  db:
    image: 'postgres:16'
    container_name: postgres_movies
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_movies_data:/var/lib/postgresql/data/
    networks:
      - movies_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_movies
    ports:
      - "3333:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_movies_data:/var/lib/pgadmin
    networks:
      - movies_network

  web:
    restart: always
    build: .
    container_name: backend_movies
    command: [ "/bin/bash", "/commands/run_web_server_prod.sh" ]
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr/src/fastapi/src
      - WATCHFILES_FORCE_POLLING=true
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/fastapi/src
    networks:
      - movies_network

  migrator:
    build: .
    container_name: alembic_migrator_movies
    command: ["/bin/bash", "/commands/run_migration.sh"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/fastapi/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/fastapi/src
    networks:
      - movies_network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog_movies
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    env_file:
      - .env
    networks:
      - movies_network

  minio:
    image: minio/minio:latest
    container_name: minio-movies
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - movies_network

  minio_mc:
    build:
      context: .
      dockerfile: docker/minio_mc/Dockerfile
    container_name: minio_mc_movies
    command: ["/bin/sh", "-c", "/commands/setup_minio.sh"]
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - movies_network

  redis:
    image: redis:7-alpine
    container_name: redis_movies
    ports:
      - "6379:6379"   # optional, for local debugging
    networks:
      - movies_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: .
    container_name: celery_worker_movies
    command: >
      celery 
      -A src.tasks.celery_app 
      worker 
      -Q default,comment_notifications,maintenance 
      --pool=solo 
      -l info
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/fastapi/src
    environment:
      - PYTHONPATH=/usr/src/fastapi/src
    networks:
      - movies_network

  celery_beat:
    build: .
    container_name: celery_beat_movies
    command: >
      celery
      -A src.tasks.celery_app.celery_app
      beat
      --loglevel=info
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/fastapi/src
    environment:
      - PYTHONPATH=/usr/src/fastapi/src
    networks:
      - movies_network

  flower:
    image: mher/flower
    container_name: flower_movies
    command:
      - celery
      - --broker=redis://redis:6379/0
      - flower
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - movies_network

volumes:
  postgres_movies_data:
    driver: local
  pgadmin_movies_data:
    driver: local
  minio_data:
    driver: local

networks:
  movies_network:
    driver: bridge
